---
run:
  deadline: 30m

linters:
  enable-all: true
  disable:
    - gochecknoglobals  # error on globals; unreliable output
    - lll               # line length check
    - unconvert         # Remove unnecessary type conversions; unreliable output
    - deadcode          # dead code; unreliable output
