# linuxkit build template 
#
# Copyright (c) 2018 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0
org: lfedge
image: eve-storage-init
network: yes
config:
  binds:
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /var:/var:rshared,rbind
    - /containers:/containers:rshared,rbind
  rootfsPropagation: shared
  capabilities:
    - all
