state = "/run/containerd-user"
root = "/persist/vault/containerd"
disabled_plugins = ["cri", "btrfs", "aufs"]

[grpc]
  address = "/run/containerd-user/containerd.sock"
  uid = 0
  gid = 0

[debug]
  address = "/run/containerd-user/debug.sock"
  level = "info"

[metrics]
  address = ""

[cgroup]
  path = "/eve/containerd"
