
required = ["github.com/linuxkit/linuxkit/src/cmd/linuxkit"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/linuxkit/linuxkit"
  revision = "7cca26e3ad28721cca67d0f2d0ac04b295d5cd7e"

[[override]]
  name = "github.com/docker/docker"
  revision = "b711437bbd8596312c962d4189e9ad4d2108c2dc"
[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"
[[override]]
  name = "github.com/docker/docker-credential-helpers"
  revision = "5241b46610f2491efdf9d1c85f1ddf5b02f6d962"
[[override]]
  name = "github.com/docker/go"
  revision = "d30aec9fd63c35133f8f79c3412ad91a3b08be06"
[[override]]
  name = "github.com/docker/go-connections"
  revision = "7beb39f0b969b075d1325fecb092faf27fd357b6"
[[override]]
  name = "github.com/docker/go-metrics"
  revision = "d466d4f6fd960e01820085bd7e1a24426ee7ef18"
[[override]]
  name = "github.com/docker/go-p9p"
  revision = "87ae8514a3a2d9684994a6c319f96ba9e18a062e"
[[override]]
  name = "github.com/docker/go-units"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"
[[override]]
  name = "github.com/docker/cli"
  version = "v18.06.0-ce"
[[override]]
  name = "github.com/radu-matei/azure-sdk-for-go"
  revision = "3b12823551999669c9a325a32472508e0af7978e"
[[override]]
  name = "github.com/radu-matei/azure-vhd-utils"
  revision = "e52754d5569d2a643a7775f72ff2a6cf524f4c25"
[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "26132835cbefa2669a306b777f34b929b56aa0a2"
[[override]]
  name = "github.com/Azure/go-ansiterm"
  revision = "d6e3b3328b783f23731bc4d058875b0371ff8109"
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d"
[[override]]
  name = "github.com/packethost/packngo"
  revision = "f1be085ecd6fca1b0a0e25eda71f208dcfcee5ab"
[[override]]
  name = "github.com/moby/hyperkit"
  revision = "d65b09c1c28a2bfb6a976c86ecd885d2ee4c71d3"
[[override]]
  name = "github.com/moby/datakit"
  revision = "97b3d230535397a813323902c23751e176481a86"
[[override]]
  name = "github.com/moby/tool"
  revision = "3dbad3b7daffd631d036493a1e883608206d2e03"
[[override]]
  name = "github.com/moby/vpnkit"
  revision = "0e4293bb1058598c4b0a406ed171f52573ef414c"
[[override]]
  name = "github.com/scaleway/scaleway-sdk-go"
  revision = "20b731586975c078d9c2d7dd0002127e9e9cdef2"
[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "52437c81da6b127a9925d17eb3a382a2e5fd395e"
[[override]]
  name = "github.com/prometheus/client_model"
  revision = "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
[[override]]
  name = "github.com/prometheus/common"
  revision = "ebdfc6da46522d58825777cf1f90490a5b1ef1d8"
[[override]]
  name = "github.com/prometheus/procfs"
  revision = "abf152e5f3e97f2fafac028d2cc06c1feb87ffa5"
[[override]]
  name = "github.com/vmware/govmomi"
  revision = "6f8ebd89d521d9f9af7a6c2219c4deee511020dd"
