---
# k3s server config file.

write-kubeconfig-mode: "0644"
cluster-init: true
log: "/var/lib/rancher/k3s/k3s.log"
debug: true
etcd-arg:
  - 'heartbeat-interval=8000'
  - 'election-timeout=40000'
etcd-expose-metrics: true
container-runtime-endpoint: "/run/containerd-user/containerd.sock"
