image: eve-debug
org: lfedge
network: yes
config:
  pid: host
  net: host
  binds:
    - /:/hostfs
    - /config:/config
    - /persist:/persist:rshared,rbind
    - /run:/run
    - /tmp:/tmp
    - /dev:/dev
    - /sys:/sys
    - /containers:/containers
    - /etc:/hostroot/etc
    - /etc/resolv.conf:/etc/resolv.conf
    - /etc/motd:/etc/motd
    - /run:/root/.ssh
    - /bin/eve:/bin/eve
    - /usr/bin/ctr:/usr/bin/ctr
    - /usr/bin/runc:/usr/bin/runc
    - /var/log:/var/log
    - /persist/containerd:/var/lib/containerd
  capabilities:
    - all
