---
name: PR build
on:
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [arm64-dirty, ubuntu-20.04]
        hv: [xen, kvm]
    steps:
      - name: Clear repository
        run: |
          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build packages
        env:
          PR_ID: ${{ github.event.pull_request.number  }}
        run: |
          make V=1 pkgs
          COMMIT_ID=$(git describe --abbrev=8 --always)
          echo "VERSION=0.0.0-pr$PR_ID-$COMMIT_ID" >> $GITHUB_ENV
          echo "TAG=evebuild/danger:pr$PR_ID" >> $GITHUB_ENV
      - name: Build EVE
        env:
          HV: ${{ matrix.hv }}
        run: |
          make V=1 ROOTFS_VERSION="$VERSION" HV=$HV eve
      - name: Export docker container
        env:
          HV: ${{ matrix.hv }}
        run: |
          ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')
          echo "ARCH=$ARCH" >> "$GITHUB_ENV"
          docker tag "lfedge/eve:$VERSION-$HV" "$TAG-$HV-$ARCH"
          IMGS="$IMGS $TAG-$HV-$ARCH"
          docker save $IMGS > eve-$HV-$ARCH.tar
      - name: Upload EVE
        uses: actions/upload-artifact@v2
        with:
          name: eve-${{ matrix.hv }}-${{ env.ARCH }}
          path: eve-${{ matrix.hv }}-${{ env.ARCH }}.tar
      - name: Clean
        if: ${{ always() }}
        run: |
          make clean
          docker system prune -f -a
          rm -rf ~/.linuxkit