---
name: PR build
on:
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [arm64-dirty, ubuntu-20.04]
    steps:
      - name: Workspace cleanup
        run: |
          # cleanup existing workspace folder if exists to not hit permission denied on checkout
          repoName="${{ github.event.repository.name }}"
          workspace="${{ github.workspace }}"
          if [ -d "$workspace" ] && [ "$(ls -A $workspace)" ]; then
            # to avoid unexpected removal of sensitive information
            # we check that workspace variable ends with repoName/repoName sequence
            if [ ! -z "$repoName" ] && [ -z "${workspace##*$repoName/$repoName}" ]; then
              ls -la "$workspace"
              docker run --rm -v "$workspace":/mnt/eve alpine find /mnt/eve -maxdepth 1 -mindepth 1 -exec rm -rvf {} \;
              ls -la "$workspace"
            fi
          fi

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build packages
        env:
          PR_ID: ${{ github.event.pull_request.number  }}
        run: |
          make V=1 pkgs
          COMMIT_ID=$(git describe --abbrev=8 --always)
          echo "VERSION=0.0.0-pr$PR_ID-$COMMIT_ID" >> $GITHUB_ENV
          echo "TAG=evebuild/danger:pr$PR_ID" >> $GITHUB_ENV
      - name: Build EVE for Xen
        run: |
          make V=1 ROOTFS_VERSION="$VERSION" HV=xen eve
      - name: Build EVE for KVM
        run: |
          rm -rf dist
          make V=1 ROOTFS_VERSION="$VERSION" HV=kvm eve
      - name: Export docker container
        run: |
          ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')
          echo "ARCH=$ARCH" >> "$GITHUB_ENV"
          for i in xen kvm; do
             docker tag "lfedge/eve:$VERSION-$i" "$TAG-$i-$ARCH"
             IMGS="$IMGS $TAG-$i-$ARCH"
          done
          docker save $IMGS > eve.tar
      - name: Upload EVE
        uses: actions/upload-artifact@v2
        with:
          name: eve-${{ env.ARCH }}
          path: eve.tar
      - name: Clean
        run: |
          make clean
          docker system prune -f -a
          rm -rf ~/.linuxkit