---
name: Publish PR build
on:
  workflow_run:
    workflows:
      - "PR build"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      RUN_ID: ${{ github.event.workflow_run.id }}
    steps:
      - name: Download PR build artifact
        id: download-pr-artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run --repo ${{ github.repository }} download ${RUN_ID}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Publish EVE
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" |\
             docker login -u evebuild --password-stdin

          find . -name '*.tar' -exec docker load --input {} \;
          docker image push --all-tags evebuild/danger

          IMGS=$(docker images --format "{{.Repository}}:{{.Tag}}"| sed -r 's/.{6}$//')
          for i in ${IMGS}; do
            docker manifest create "$i" --amend "$i-arm64" --amend "$i-amd64"
            docker manifest push "$i"
          done
