---
name: Test Eden WF from lf-edge/eden
on:
  workflow_dispatch:

jobs:
  test_suite:
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "evebuild/danger:pr${{ github.event.pull_request.number  }}"
