---
name: lf-edge/eden Test suite

on: # yamllint disable-line rule:truthy
  pull_request_review:
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
    paths-ignore:
      - 'docs/**'
      - 'pkg/pillar/docs/**'
  pull_request:
    types: [labeled]
    paths-ignore:
      - 'docs/**'
      - 'pkg/pillar/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "test-eden"
        REMOVE_LABEL: "awaiting%20review"

  test_suite_pr:
    if: ${{ github.event.label.name  == 'test-eden' }}
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "evebuild/danger:pr${{ github.event.pull_request.number  }}"

  test_suite_master:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "lfedge/eve:snapshot"

  test_suite_tag:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "lfedge/eve:${{  github.ref_name }}"
