---
name: lf-edge/eden Test suite

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
    paths-ignore:
      - 'docs/**'
      - 'pkg/pillar/docs/**'
  pull_request_review:
    types: [submitted]
    paths-ignore:
      - 'docs/**'
      - 'pkg/pillar/docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_suite_pr:
    if: ${{ (github.event.review.state == 'approved') &&  ( github.event_name == 'pull_request') }}
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "evebuild/danger:pr${{ github.event.pull_request.number  }}"

  test_suite_master:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "lfedge/eve:snapshot"

  test_suite_tag:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    uses: lf-edge/eden/.github/workflows/test.yml@master
    with:
      eve_image: "lfedge/eve:${{  github.ref_name }}"
