---
name: Publish
on:
  push:
    branches:
      - "master"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ARM64, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHUB
        run: |
          echo "${{ secrets.RELEASE_DOCKERHUB_TOKEN }}" |\
             docker login -u "${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}" --password-stdin
      - name: Build packages
        run: |
          # FIXME: this needs to be updated in the build image
          if [ "$(uname -m)" = aarch64 ]; then
             sudo apt install -y jq || :
             docker rmi -f `docker image ls -q` || :
             docker system prune -f || :
          fi
          # GH Actions convert our annotated tags into plain ones,
          # so we need to convert it back (but only if it exists).
          if [ -n "$(git tag)" ]; then
             git config --global user.name "Edge Virtualization Engine"
             git config --global user.email "eve@lfedge.org"
             git tag -a -m"Release $(git tag)" -f $(git tag) $(git tag)
          fi
          # sadly, our build sometimes times out on network access
          # re-trying for 3 times if needed
          for i in 1 2 3; do
             if make LINUXKIT_PKG_TARGET=push pkgs; then
                break
             fi
          done
      - name: Build EVE
        run: |
          make LINUXKIT_PKG_TARGET=push eve
      - name: Build EVE for KVM
        run: |
          rm -rf dist
          make LINUXKIT_PKG_TARGET=push HV=kvm eve
