---
name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build packages
        run: |
          make pkgs
      - name: Build EVE
        run: |
          make eve
      - name: Build EVE for KVM
        run: |
          rm -rf dist
          make HV=kvm eve
